export const ActivityIcons: Record<'sports', Record<string, string>> = {
    sports: {
        Running: '🏃‍♂️',
        Golf: '🏌️‍♂️',
        Gymnastics: '🤸‍♀️',
        'Ice Hockey': '🏒',
        Cycling: '🚴‍♂️',
        Athletics: '🏃‍♀️',
        Handball: '🤾‍♂️',
        Football: '⚽',
        Swimming: '🏊‍♂️',
        Rugby: '🏉',
        Gym: '🏋️‍♂️',
        Volleyball: '🏐',
        'Ski Jumping': '⛷️',
        Walking: '🚶‍♂️',
        'Martial Arts': '🥋',
        Motorsports: '🏎️',
        'Rollerblading / Skateboarding': '🛹',
        Tennis: '🎾',
        Rowing: '🚣‍♂️',
        Skiing: '⛷️',
    },
};
